# Generated by Django 6.0.2 on 2026-02-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_personnel', '0003_employee_core_hr_fields'),
        ('organizations', '0004_organization_personnel_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('unpaid', 'Unpaid'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('haj', 'Haj')], max_length=20, verbose_name='Leave Type')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Days')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/%Y/%m/', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr_personnel.employee')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('auto_approval', 'Auto Approval Suggestion'), ('abuse_detection', 'Abuse Detection'), ('staff_shortage', 'Staff Shortage Prediction')], max_length=30, verbose_name='Insight Type')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score')),
                ('recommendation', models.CharField(max_length=255, verbose_name='Recommendation')),
                ('rationale', models.TextField(blank=True, null=True, verbose_name='Rationale')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='hr_personnel.leaverequest')),
            ],
            options={
                'verbose_name': 'Leave AI Insight',
                'verbose_name_plural': 'Leave AI Insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('unpaid', 'Unpaid'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('haj', 'Haj')], max_length=20, verbose_name='Leave Type')),
                ('accrual_method', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, verbose_name='Accrual Method')),
                ('accrual_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Accrual Rate')),
                ('carry_forward_allowed', models.BooleanField(default=False, verbose_name='Carry Forward Allowed')),
                ('max_carry_forward', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Max Carry Forward')),
                ('encashable', models.BooleanField(default=False, verbose_name='Encashable')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requires Approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'unique_together': {('organization', 'leave_type')},
            },
        ),
    ]
