# Generated by Django 6.0.2 on 2026-03-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_personnel', '0007_work_units_and_supply_company'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='salarycomponent',
                    old_name='salary_profile',
                    new_name='salary_structure',
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='calculation_frequency',
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='calculation_method',
            field=models.CharField(choices=[('fixed_monthly', 'Fixed Monthly'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour')], db_column='calculation_frequency', default=1, max_length=20, verbose_name='Calculation Method'),
            preserve_default=False,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameModel(
                    old_name='SalaryProfile',
                    new_name='SalaryStructure',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='item_type',
            field=models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='component_type',
            field=models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterModelTable(
            name='salarycomponent',
            table='hr_personnel_salarycomponent',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='salarystructure',
                    table='hr_personnel_salaryprofile',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='salarycomponent',
                    name='salary_structure',
                    field=models.ForeignKey(db_column='salary_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr_personnel.salarystructure'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='payrollslip',
                    name='salary_profile',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_slips', to='hr_personnel.salarystructure'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['salary_structure', 'is_active'], name='hr_personne_salary__8de176_idx'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['component_type', 'calculation_method'], name='hr_personne_compone_63f189_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['employee', 'is_active'], name='hr_personne_employe_a5eb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['employee', 'effective_from'], name='hr_personne_employe_ea9456_idx'),
        ),
    ]
