# Generated by Django 6.0.2 on 2026-03-09 07:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.utils import OperationalError


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except OperationalError as exc:
            message = str(exc).lower()
            if (
                'duplicate column name' in message
                or ('column' in message and 'exists' in message)
                or ('duplicate key name' in message)
                or ('key column' in message and "doesn't exist in table" in message)
            ):
                return
            raise


class CreateModelIfNotExists(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except OperationalError as exc:
            message = str(exc).lower()
            if (
                'already exists' in message
                or ('table' in message and 'exists' in message)
                or ('key column' in message and "doesn't exist in table" in message)
            ):
                return
            raise


class Migration(migrations.Migration):

    dependencies = [
        ('hr_personnel', '0008_remove_salaryprofile_employee_and_more'),
        ('organizations', '0004_organization_personnel_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'ordering': ['-effective_from'], 'verbose_name': 'Salary Structure', 'verbose_name_plural': 'Salary Structures'},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='salarystructure',
                    old_name='compensation_basis',
                    new_name='pay_type',
                ),
                migrations.AlterField(
                    model_name='salarystructure',
                    name='pay_type',
                    field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], db_column='compensation_basis', default='monthly', max_length=20, verbose_name='Pay Type'),
                ),
            ],
            database_operations=[],
        ),
        AddFieldIfNotExists(
            model_name='payrollitem',
            name='component_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Component Name'),
        ),
        AddFieldIfNotExists(
            model_name='payrollitem',
            name='component_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Component Type'),
        ),
        AddFieldIfNotExists(
            model_name='payrollslip',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Generated At'),
            preserve_default=False,
        ),
        AddFieldIfNotExists(
            model_name='payrollslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Gross Salary'),
        ),
        AddFieldIfNotExists(
            model_name='payrollslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Net Salary'),
        ),
        AddFieldIfNotExists(
            model_name='payrollslip',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Overtime Amount'),
        ),
        migrations.AlterField(
            model_name='payrollslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='hr_personnel.employee'),
        ),
        CreateModelIfNotExists(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Period Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('review', 'Review'), ('finalized', 'Finalized')], default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        AddFieldIfNotExists(
            model_name='payrollslip',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips', to='hr_personnel.payrollperiod'),
        ),
        CreateModelIfNotExists(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_date', models.DateTimeField(auto_now_add=True, verbose_name='Run Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('execution_ms', models.PositiveIntegerField(default=0, verbose_name='Execution Time (ms)')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='hr_personnel.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-run_date'],
            },
        ),
        AddFieldIfNotExists(
            model_name='payrollrun',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='hr_personnel.payrollperiod'),
        ),
        AddFieldIfNotExists(
            model_name='payrollrun',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        AddFieldIfNotExists(
            model_name='payrollrun',
            name='execution_ms',
            field=models.PositiveIntegerField(default=0, verbose_name='Execution Time (ms)'),
        ),
    ]
