# Generated by Django 6.0.2 on 2026-03-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_personnel', '0014_employee_attendance_tag_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('review', 'Review'), ('finalized', 'Finalized'), ('canceled', 'Canceled')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
