# Generated by Django 6.0.2 on 2026-02-20 12:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_personnel', '0004_leaverequest_leaveaiinsight_leavepolicy'),
        ('organizations', '0004_organization_personnel_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('OM', 'Oman'), ('IR', 'Iran')], max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_currency', models.CharField(default='OMR', max_length=8)),
                ('wps_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_company', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='hrms.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('nationality', models.CharField(blank=True, max_length=64, null=True)),
                ('hire_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('ai_risk_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnel_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_employee_profile', to='hr_personnel.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrms.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(db_index=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('biometric', 'Biometric'), ('mobile', 'Mobile'), ('web', 'Web'), ('manual', 'Manual')], default='web', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='hrms.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(choices=[('OM', 'Oman'), ('IR', 'Iran')], max_length=2)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_policies', to='hrms.company')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_month', models.DateField()),
                ('predicted_minutes', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('model_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_predictions', to='hrms.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_predictions', to='hrms.company')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeRateRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_type', models.CharField(choices=[('working_day', 'Working Day'), ('weekend', 'Weekend'), ('public_holiday', 'Public Holiday'), ('ramadan_special', 'Ramadan Special')], max_length=20)),
                ('overtime_type', models.CharField(choices=[('normal', 'Normal'), ('night', 'Night'), ('holiday', 'Holiday')], default='normal', max_length=20)),
                ('rate_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6)),
                ('min_minutes_threshold', models.PositiveIntegerField(default=0)),
                ('max_minutes_per_day', models.PositiveIntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='hrms.overtimepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollOvertimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('total_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('total_overtime_pay', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_overtime_entries', to='hrms.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_overtime_entries', to='hrms.company')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='hrms.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hrms.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shift_assignments', to='hrms.company')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='hrms.shifttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField(db_index=True)),
                ('valid_to', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('required_work_minutes', models.PositiveIntegerField(default=480)),
                ('grace_in_minutes', models.PositiveIntegerField(default=0)),
                ('grace_out_minutes', models.PositiveIntegerField(default=0)),
                ('is_ramadan_shift', models.BooleanField(default=False)),
                ('is_summer_shift', models.BooleanField(default=False)),
                ('overtime_after_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hrms.shifttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_versions', to='hrms.company')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_in', models.DateTimeField(blank=True, null=True)),
                ('actual_out', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('required_minutes', models.PositiveIntegerField(default=0)),
                ('normal_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('weekend_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('holiday_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_leave_minutes', models.PositiveIntegerField(default=0)),
                ('is_absent', models.BooleanField(default=False)),
                ('anomaly_flag', models.BooleanField(default=False)),
                ('overtime_pay_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('ai_features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='hrms.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='hrms.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('day_type', models.CharField(choices=[('working', 'Working Day'), ('weekend', 'Weekend'), ('public_holiday', 'Public Holiday'), ('special', 'Special')], default='working', max_length=20)),
                ('holiday_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ramadan', models.BooleanField(default=False)),
                ('is_summer_schedule', models.BooleanField(default=False)),
                ('standard_work_minutes', models.PositiveIntegerField(default=480)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendar_days', to='hrms.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['country'], name='hrms_compan_country_08157a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='hrms_compan_created_18d481_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='hrms_auditl_tenant__0758ff_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='hrms_auditl_user_id_3937ae_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'employee_code'], name='hrms_employ_tenant__06fb45_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_active'], name='hrms_employ_tenant__54d32d_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee_code'), name='uq_hrms_employee_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['tenant', 'employee', 'check_in'], name='hrms_attend_tenant__cb3aed_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimepolicy',
            index=models.Index(fields=['tenant', 'country', 'effective_from'], name='hrms_overti_tenant__8e1c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeprediction',
            index=models.Index(fields=['tenant', 'target_month'], name='hrms_overti_tenant__7dc830_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeraterule',
            index=models.Index(fields=['policy', 'day_type', 'overtime_type'], name='hrms_overti_policy__270123_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollovertimeentry',
            index=models.Index(fields=['tenant', 'period_year', 'period_month'], name='hrms_payrol_tenant__53b214_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollovertimeentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'period_year', 'period_month'), name='uq_hrms_payroll_ot_tenant_employee_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollovertimeentry',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='ck_hrms_payroll_ot_month_range'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_hrms_shifttemplate_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['tenant', 'employee', 'effective_from'], name='hrms_employ_tenant__37878a_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeshiftassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_hrms_shift_assignment_effective_range'),
        ),
        migrations.AddIndex(
            model_name='shiftversion',
            index=models.Index(fields=['tenant', 'shift', 'valid_from'], name='hrms_shiftv_tenant__b767b1_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftversion',
            index=models.Index(fields=['tenant', 'shift', 'valid_to'], name='hrms_shiftv_tenant__692de3_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='ck_hrms_shiftversion_valid_range'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'work_date'], name='hrms_timesh_tenant__bd0cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'employee', 'work_date'], name='hrms_timesh_tenant__ab5eac_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'work_date'), name='uq_hrms_timesheet_tenant_employee_workdate'),
        ),
        migrations.AddIndex(
            model_name='workcalendar',
            index=models.Index(fields=['tenant', 'date'], name='hrms_workca_tenant__1d6589_idx'),
        ),
        migrations.AddIndex(
            model_name='workcalendar',
            index=models.Index(fields=['tenant', 'day_type'], name='hrms_workca_tenant__093a9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='workcalendar',
            constraint=models.UniqueConstraint(fields=('tenant', 'date'), name='uq_hrms_workcalendar_tenant_date'),
        ),
    ]
