# Generated by Django 6.0.2 on 2026-03-06 20:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _drop_partial_tables_if_exist(apps, schema_editor):
    table_names = [
        'hrms_workclosure',
        'hrms_workunitshiftassignment',
    ]

    with schema_editor.connection.cursor() as cursor:
        for table_name in table_names:
            quoted_name = schema_editor.quote_name(table_name)
            cursor.execute(f"DROP TABLE IF EXISTS {quoted_name}")


def _safe_rename_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    rename_pairs = [
        ('hrms_leavebalance', 'hrms_leaveb_tenant__13aa0c_idx', 'hrms_leaveb_tenant__fd51aa_idx'),
        ('hrms_leaverequest', 'hrms_leaver_tenant__14100a_idx', 'hrms_leaver_tenant__c485d5_idx'),
        ('hrms_leaverequest', 'hrms_leaver_tenant__f22793_idx', 'hrms_leaver_tenant__0efc7a_idx'),
        ('hrms_leavetype', 'hrms_leavet_tenant__a1f3d6_idx', 'hrms_leavet_tenant__e84a16_idx'),
        ('hrms_leavetype', 'hrms_leavet_tenant__2480d8_idx', 'hrms_leavet_tenant__88be02_idx'),
        ('hrms_overtimeprediction', 'hrms_overti_tenant__4b0fb5_idx', 'hrms_overti_tenant__60f6c1_idx'),
        ('hrms_payrollperiod', 'hrms_payrol_tenant__5fb8dc_idx', 'hrms_payrol_tenant__8f1949_idx'),
        ('hrms_payrollperiod', 'hrms_payrol_tenant__ef0382_idx', 'hrms_payrol_tenant__9848ca_idx'),
        ('hrms_payrollresult', 'hrms_payrol_tenant__5fbc8d_idx', 'hrms_payrol_tenant__bad7bb_idx'),
        ('hrms_salarystructure', 'hrms_salary_tenant__817ca4_idx', 'hrms_salary_tenant__6db672_idx'),
    ]

    with schema_editor.connection.cursor() as cursor:
        for table_name, old_index_name, new_index_name in rename_pairs:
            cursor.execute(f"SHOW INDEX FROM `{table_name}` WHERE Key_name = %s", [old_index_name])
            old_exists = cursor.fetchone() is not None
            cursor.execute(f"SHOW INDEX FROM `{table_name}` WHERE Key_name = %s", [new_index_name])
            new_exists = cursor.fetchone() is not None

            if old_exists and not new_exists:
                cursor.execute(
                    f"ALTER TABLE `{table_name}` RENAME INDEX `{old_index_name}` TO `{new_index_name}`"
                )


def _ensure_leavetype_payroll_columns(apps, schema_editor):
    LeaveType = apps.get_model('hrms', 'LeaveType')
    table_name = LeaveType._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'deduct_from_payroll' not in existing_columns:
        field = models.BooleanField(default=False)
        field.set_attributes_from_name('deduct_from_payroll')
        schema_editor.add_field(LeaveType, field)

    if 'deduction_rate_percent' not in existing_columns:
        field = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('0.00'))
        field.set_attributes_from_name('deduction_rate_percent')
        schema_editor.add_field(LeaveType, field)


def _ensure_work_assignment_fk_columns(apps, schema_editor):
    auth_app_label, auth_model_name = settings.AUTH_USER_MODEL.split('.')

    UserModel = apps.get_model(auth_app_label, auth_model_name)
    Company = apps.get_model('hrms', 'Company')
    ShiftTemplate = apps.get_model('hrms', 'ShiftTemplate')
    WorkUnit = apps.get_model('hr_personnel', 'WorkUnit')
    WorkClosure = apps.get_model('hrms', 'WorkClosure')
    WorkUnitShiftAssignment = apps.get_model('hrms', 'WorkUnitShiftAssignment')

    def _existing_columns(model):
        with schema_editor.connection.cursor() as cursor:
            return {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(cursor, model._meta.db_table)
            }

    closure_columns = _existing_columns(WorkClosure)
    if 'created_by_id' not in closure_columns:
        field = models.ForeignKey(UserModel, on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, db_constraint=False)
        field.set_attributes_from_name('created_by')
        schema_editor.add_field(WorkClosure, field)
    if 'tenant_id' not in closure_columns:
        field = models.ForeignKey(Company, on_delete=django.db.models.deletion.CASCADE, db_constraint=False)
        field.set_attributes_from_name('tenant')
        schema_editor.add_field(WorkClosure, field)
    if 'work_unit_id' not in closure_columns:
        field = models.ForeignKey(WorkUnit, on_delete=django.db.models.deletion.CASCADE, null=True, blank=True, db_constraint=False)
        field.set_attributes_from_name('work_unit')
        schema_editor.add_field(WorkClosure, field)

    assignment_columns = _existing_columns(WorkUnitShiftAssignment)
    if 'shift_id' not in assignment_columns:
        field = models.ForeignKey(ShiftTemplate, on_delete=django.db.models.deletion.CASCADE, db_constraint=False)
        field.set_attributes_from_name('shift')
        schema_editor.add_field(WorkUnitShiftAssignment, field)
    if 'tenant_id' not in assignment_columns:
        field = models.ForeignKey(Company, on_delete=django.db.models.deletion.CASCADE, db_constraint=False)
        field.set_attributes_from_name('tenant')
        schema_editor.add_field(WorkUnitShiftAssignment, field)
    if 'work_unit_id' not in assignment_columns:
        field = models.ForeignKey(WorkUnit, on_delete=django.db.models.deletion.CASCADE, db_constraint=False)
        field.set_attributes_from_name('work_unit')
        schema_editor.add_field(WorkUnitShiftAssignment, field)


class Migration(migrations.Migration):

    dependencies = [
        ('hr_personnel', '0008_remove_salaryprofile_employee_and_more'),
        ('hrms', '0002_leave_payroll_ess_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_drop_partial_tables_if_exist, migrations.RunPython.noop),
        migrations.CreateModel(
            name='WorkClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('scope', models.CharField(choices=[('company', 'Company-wide'), ('work_unit', 'Work Unit')], default='company', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_paid', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkUnitShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(_safe_rename_indexes, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_ensure_leavetype_payroll_columns, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='leavetype',
                    name='deduct_from_payroll',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='leavetype',
                    name='deduction_rate_percent',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_ensure_work_assignment_fk_columns, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='workclosure',
                    name='created_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_closures', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='workclosure',
                    name='tenant',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_closures', to='hrms.company'),
                ),
                migrations.AddField(
                    model_name='workclosure',
                    name='work_unit',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_closures', to='hr_personnel.workunit'),
                ),
                migrations.AddField(
                    model_name='workunitshiftassignment',
                    name='shift',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_unit_assignments', to='hrms.shifttemplate'),
                ),
                migrations.AddField(
                    model_name='workunitshiftassignment',
                    name='tenant',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_unit_shift_assignments', to='hrms.company'),
                ),
                migrations.AddField(
                    model_name='workunitshiftassignment',
                    name='work_unit',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_shift_assignments', to='hr_personnel.workunit'),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='workclosure',
            index=models.Index(fields=['tenant', 'scope', 'start_date'], name='hrms_workcl_tenant__d7b529_idx'),
        ),
        migrations.AddIndex(
            model_name='workclosure',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='hrms_workcl_tenant__25d1e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='workclosure',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_hrms_work_closure_date_range'),
        ),
        migrations.AddIndex(
            model_name='workunitshiftassignment',
            index=models.Index(fields=['tenant', 'work_unit', 'effective_from'], name='hrms_workun_tenant__2284fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='workunitshiftassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_hrms_work_unit_shift_assignment_effective_range'),
        ),
    ]
