# Generated by Django 6.0.2 on 2026-03-08 10:07

from django.db import migrations


def _safe_rename_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    rename_pairs = [
        ('hrms_leavebalance', 'hrms_leaveb_tenant__13aa0c_idx', 'hrms_leaveb_tenant__fd51aa_idx'),
        ('hrms_leaverequest', 'hrms_leaver_tenant__14100a_idx', 'hrms_leaver_tenant__c485d5_idx'),
        ('hrms_leaverequest', 'hrms_leaver_tenant__f22793_idx', 'hrms_leaver_tenant__0efc7a_idx'),
        ('hrms_leavetype', 'hrms_leavet_tenant__a1f3d6_idx', 'hrms_leavet_tenant__e84a16_idx'),
        ('hrms_leavetype', 'hrms_leavet_tenant__2480d8_idx', 'hrms_leavet_tenant__88be02_idx'),
        ('hrms_overtimeprediction', 'hrms_overti_tenant__4b0fb5_idx', 'hrms_overti_tenant__60f6c1_idx'),
        ('hrms_payrollperiod', 'hrms_payrol_tenant__5fb8dc_idx', 'hrms_payrol_tenant__8f1949_idx'),
        ('hrms_payrollperiod', 'hrms_payrol_tenant__ef0382_idx', 'hrms_payrol_tenant__9848ca_idx'),
        ('hrms_payrollresult', 'hrms_payrol_tenant__5fbc8d_idx', 'hrms_payrol_tenant__bad7bb_idx'),
        ('hrms_salarystructure', 'hrms_salary_tenant__817ca4_idx', 'hrms_salary_tenant__6db672_idx'),
    ]

    with schema_editor.connection.cursor() as cursor:
        for table_name, old_index_name, new_index_name in rename_pairs:
            cursor.execute(f"SHOW INDEX FROM `{table_name}` WHERE Key_name = %s", [old_index_name])
            old_exists = cursor.fetchone() is not None
            cursor.execute(f"SHOW INDEX FROM `{table_name}` WHERE Key_name = %s", [new_index_name])
            new_exists = cursor.fetchone() is not None

            if old_exists and not new_exists:
                cursor.execute(
                    f"ALTER TABLE `{table_name}` RENAME INDEX `{old_index_name}` TO `{new_index_name}`"
                )


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_workclosure_workunitshiftassignment_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_safe_rename_indexes, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='leavebalance',
                    new_name='hrms_leaveb_tenant__fd51aa_idx',
                    old_name='hrms_leaveb_tenant__13aa0c_idx',
                ),
                migrations.RenameIndex(
                    model_name='leaverequest',
                    new_name='hrms_leaver_tenant__c485d5_idx',
                    old_name='hrms_leaver_tenant__14100a_idx',
                ),
                migrations.RenameIndex(
                    model_name='leaverequest',
                    new_name='hrms_leaver_tenant__0efc7a_idx',
                    old_name='hrms_leaver_tenant__f22793_idx',
                ),
                migrations.RenameIndex(
                    model_name='leavetype',
                    new_name='hrms_leavet_tenant__e84a16_idx',
                    old_name='hrms_leavet_tenant__a1f3d6_idx',
                ),
                migrations.RenameIndex(
                    model_name='leavetype',
                    new_name='hrms_leavet_tenant__88be02_idx',
                    old_name='hrms_leavet_tenant__2480d8_idx',
                ),
                migrations.RenameIndex(
                    model_name='overtimeprediction',
                    new_name='hrms_overti_tenant__60f6c1_idx',
                    old_name='hrms_overti_tenant__4b0fb5_idx',
                ),
                migrations.RenameIndex(
                    model_name='payrollperiod',
                    new_name='hrms_payrol_tenant__8f1949_idx',
                    old_name='hrms_payrol_tenant__5fb8dc_idx',
                ),
                migrations.RenameIndex(
                    model_name='payrollperiod',
                    new_name='hrms_payrol_tenant__9848ca_idx',
                    old_name='hrms_payrol_tenant__ef0382_idx',
                ),
                migrations.RenameIndex(
                    model_name='payrollresult',
                    new_name='hrms_payrol_tenant__bad7bb_idx',
                    old_name='hrms_payrol_tenant__5fbc8d_idx',
                ),
                migrations.RenameIndex(
                    model_name='salarystructure',
                    new_name='hrms_salary_tenant__6db672_idx',
                    old_name='hrms_salary_tenant__817ca4_idx',
                ),
            ],
        ),
    ]
