# Generated by Django 6.0.2 on 2026-03-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_personnel', '0017_employee_supply_company_fix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salarycomponent',
            new_name='hr_personne_salary__0d794b_idx',
            old_name='hr_personne_salary__8de176_idx',
        ),
        migrations.RenameIndex(
            model_name='salarystructure',
            new_name='hr_personne_employe_c7b452_idx',
            old_name='hr_personne_employe_a5eb0a_idx',
        ),
        migrations.RenameIndex(
            model_name='salarystructure',
            new_name='hr_personne_employe_8f088f_idx',
            old_name='hr_personne_employe_ea9456_idx',
        ),
    ]
