services:
  - type: web
    name: pc-software
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: USE_SQLITE
        value: "0"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_CA
        sync: false
    healthCheckPath: /
