# Generated by Django 6.0.2 on 2026-02-19 18:02

import django.db.models.deletion
from django.db import migrations, models
from django.db.utils import OperationalError


class CreateModelIfNotExists(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except OperationalError as exc:
            message = str(exc).lower()
            if 'already exists' in message or 'table' in message and 'exists' in message:
                return
            raise


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except OperationalError as exc:
            message = str(exc).lower()
            if 'duplicate column name' in message or ('column' in message and 'exists' in message):
                return
            raise


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('hr_attendance', '0005_attendance_clock_locations'),
        ('hr_personnel', '0003_employee_core_hr_fields'),
    ]

    operations = [
        CreateModelIfNotExists(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=120, verbose_name='Shift Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('grace_in', models.PositiveIntegerField(default=0, verbose_name='Grace In (minutes)')),
                ('grace_out', models.PositiveIntegerField(default=0, verbose_name='Grace Out (minutes)')),
                ('overtime_policy_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Overtime Policy ID')),
                ('is_night_shift', models.BooleanField(default=False, verbose_name='Is Night Shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['shift_name'],
            },
        ),
        AddFieldIfNotExists(
            model_name='attendance',
            name='capture_mode',
            field=models.CharField(choices=[('biometric', 'Biometric'), ('mobile_gps', 'Mobile GPS'), ('web_punch', 'Web Punch'), ('manual', 'Manual'), ('face_recognition', 'Face Recognition'), ('geofencing', 'Geofencing')], default='web_punch', max_length=30, verbose_name='Capture Mode'),
        ),
        AddFieldIfNotExists(
            model_name='attendance',
            name='device_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Device ID'),
        ),
        AddFieldIfNotExists(
            model_name='attendance',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Location Latitude'),
        ),
        AddFieldIfNotExists(
            model_name='attendance',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Location Longitude'),
        ),
        AddFieldIfNotExists(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('device', 'Device'), ('mobile', 'Mobile'), ('web', 'Web'), ('manual', 'Manual')], default='web', max_length=20, verbose_name='Source'),
        ),
        AddFieldIfNotExists(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', max_length=10, verbose_name='Status'),
        ),
        CreateModelIfNotExists(
            name='AttendanceAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('fraud_detection', 'Fraud Detection'), ('absence_prediction', 'Absence Prediction'), ('shift_optimization', 'Shift Optimization'), ('late_pattern', 'Late Pattern Detection')], max_length=40, verbose_name='Insight Type')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Recommendation')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('employee', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_ai_insights', to='hr_personnel.employee')),
            ],
            options={
                'verbose_name': 'Attendance AI Insight',
                'verbose_name_plural': 'Attendance AI Insights',
                'ordering': ['-generated_at'],
            },
        ),
        AddFieldIfNotExists(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='hr_attendance.shift', verbose_name='Shift'),
        ),
        CreateModelIfNotExists(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Work Date')),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Worked Hours')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Overtime Hours')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Late Minutes')),
                ('early_leave_minutes', models.PositiveIntegerField(default=0, verbose_name='Early Leave Minutes')),
                ('absence_flag', models.BooleanField(default=False, verbose_name='Absence Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='hr_personnel.employee', verbose_name='Employee')),
                ('source_attendance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_timesheets', to='hr_attendance.attendance')),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
                'ordering': ['-work_date'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
