# Generated by Django 6.0.2 on 2026-03-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_ticketreadreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_response', 'Waiting for Response'), ('user_new_message', 'User New Message'), ('answered', 'Answered'), ('under_review', 'Under Review'), ('referred', 'Referred to Expert'), ('in_progress', 'In Progress'), ('needs_info', 'Needs More Info'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
