# Generated by Django 6.0.2 on 2026-02-18 06:27

from django.db import migrations, models


def add_timezone_if_missing(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    table_name = UserProfile._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'timezone' in columns:
        return

    field = models.CharField(
        max_length=64,
        default='Asia/Tehran',
        help_text='IANA timezone (e.g. Asia/Tehran)',
    )
    field.set_attributes_from_name('timezone')
    schema_editor.add_field(UserProfile, field)


def remove_timezone_if_exists(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    table_name = UserProfile._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'timezone' not in columns:
        return

    field = models.CharField(
        max_length=64,
        default='Asia/Tehran',
        help_text='IANA timezone (e.g. Asia/Tehran)',
    )
    field.set_attributes_from_name('timezone')
    schema_editor.remove_field(UserProfile, field)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_supervisor'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_timezone_if_missing, remove_timezone_if_exists),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='timezone',
                    field=models.CharField(default='Asia/Tehran', help_text='IANA timezone (e.g. Asia/Tehran)', max_length=64),
                ),
            ],
        ),
    ]
